In [6]:
# Adding Violations to NYCHA Addresses

In [1]:
import pandas as pd
from joblib import load

In [2]:
addresses_df = pd.read_csv("../processed_data/cleaned_fuzzy_matching.csv")
nycha_df = pd.read_csv("../data/nycha.csv")
borough_map = load('borough_map.joblib')

In [5]:
addresses_df.head()

,nycha_idx,hpd_inx,nycha_address,hpd_address,score
0,0,3195153,1 LORRAINE STREET BROOKLYN 11231,1 LORRAINE STREET BROOKLYN 11231,100.000000
1,3,778118,621 EAST 105 STREET BROOKLYN 11236,621 EAST 102 STREET BROOKLYN 11236,97.058824
2,10,14153,1605 EAST 174 STREET BRONX 10472,1670 EAST 174 STREET BRONX 10472,96.875000
3,12,65564,147 RICHARDS STREET BROOKLYN 11231,179 RICHARDS STREET BROOKLYN 11231,97.058824
4,16,205173,1591 PARK AVENUE MANHATTAN 10029,1351 PARK AVENUE MANHATTAN 10029,96.875000

In [8]:
nycha_df.head()

,Violation ID,Primary Building Identifier,Primary Boro Identifier,Primary Borough Name,Primary House Number,Primary Low House Number,Primary High House Number,Primary Street Name,Primary Postcode,Development Name,...,Order Number,Issued in Error,Latitude,Longitude,Community Board,Council District,BIN,BBL,Census Tract (2020),Neighborhood Tabulation Area (NTA) (2020)
0,18220152,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,508,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601
1,18220153,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,583,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601
2,18220154,808768,3,BROOKLYN,1,1,17,LORRAINE STREET,11231,RED HOOK WEST,...,508,N,40.675118,-74.009568,306,38,3326207.0,3.005330e+09,85,BK0601
3,18223815,286990,3,BROOKLYN,621,615,621,EAST 105 STREET,11236,BREUKELEN,...,508,N,40.650186,-73.897621,318,42,3321415.0,3.081740e+09,982,BK1803
4,18223816,286990,3,BROOKLYN,621,615,621,EAST 105 STREET,11236,BREUKELEN,...,550,N,40.650186,-73.897621,318,42,3321415.0,3.081740e+09,982,BK1803

In [7]:
# for each address in addresses_df check datasets for all vios with that address 

# borough_map = {
#     "BROOKLYN": hpd_brooklyn['Full_Address'].tolist(),
#     "BRONX": hpd_bronx['Full_Address'].tolist(),
#     "MANHATTAN": hpd_manhattan['Full_Address'].tolist(),
#     "QUEENS": hpd_queens['Full_Address'].tolist(),
#     "STATEN ISLAND": hpd_si['Full_Address'].tolist()
# }

borough_map['BROOKLYN']

['22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '118 FENIMORE STREET BROOKLYN 11225',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '1601 OCEAN PARKWAY BROOKLYN 11223',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '118 FENIMORE STREET BROOKLYN 11225',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '22 FRONT STAGG STREET BROOKLYN 11206',
 '55 LENOX ROAD BROOKLYN 11226',
 '308 ELLERY STREET BROOKLYN 11206',
 '118 FENIMORE STREET BROOKLYN 11225',
 '518 BRISTOL STREET BROOKLYN 11212',
 '118 FENIMORE STREET BROOKLYN 11225',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '1700 BEDFORD AVENUE BROOKLYN 11225',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '775 ST JOHNS PLACE BROOKLYN 11216',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '2349 PITKIN AVENUE BROOKLYN 11207',
 '697 CONEY ISLAND AVENUE BROOKLYN 11218',
 '86 LINCOLN ROAD BROOKLYN 11225',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '567 50 STREET BROOKLYN 11220',
 '2211 DITMAS AVENUE BROOKLYN 11226',
 '2211 DITMAS AVENUE BROOKLYN 11226',
 '5203 5 AVENUE BROOKLYN 11220',
 '5203 5 AVENUE BROOKLYN 11220',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '5203 5 AVENUE BROOKLYN 11220',
 '5203 5 AVENUE BROOKLYN 11220',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '697 CONEY ISLAND AVENUE BROOKLYN 11218',
 '409 SUYDAM STREET BROOKLYN 11237',
 '318 EAST 16 STREET BROOKLYN 11226',
 '697 CONEY ISLAND AVENUE BROOKLYN 11218',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '147 HULL STREET BROOKLYN 11233',
 '147 HULL STREET BROOKLYN 11233',
 '305 LINDEN BOULEVARD BROOKLYN 11226',
 '147 HULL STREET BROOKLYN 11233',
 '905 MOTHER GASTON BOULEVARD BROOKLYN 11212',
 '1700 BEDFORD AVENUE BROOKLYN 11225',
 '774 ROCKAWAY AVENUE BROOKLYN 11212',
 '8797 25 AVENUE BROOKLYN 11214',
 '8797 25 AVENUE BROOKLYN 11214',
 '1700 BEDFORD AVENUE BROOKLYN 11225',
 '697 CONEY ISLAND AVENUE BROOKLYN 11218',
 '55 LENOX ROAD BROOKLYN 11226',
 '1106 REMSEN AVENUE BROOKLYN 11236',
 '28 COLUMBIA PLACE BROOKLYN 11201',
 '28 COLUMBIA PLACE BROOKLYN 11201',
 '28 COLUMBIA PLACE BROOKLYN 11201',
 '28 COLUMBIA PLACE BROOKLYN 11201',
 '28 COLUMBIA PLACE BROOKLYN 11201',
 '55 LENOX ROAD BROOKLYN 11226',
 '28 COLUMBIA PLACE BROOKLYN 11201',
 '28 COLUMBIA PLACE BROOKLYN 11201',
 '28 COLUMBIA PLACE BROOKLYN 11201',
 '28 COLUMBIA PLACE BROOKLYN 11201',
 '28 COLUMBIA PLACE BROOKLYN 11201',
 '28 COLUMBIA PLACE BROOKLYN 11201',
 '28 COLUMBIA PLACE BROOKLYN 11201',
 '28 COLUMBIA PLACE BROOKLYN 11201',
 '151 CONOVER STREET BROOKLYN 11231',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '518 BRISTOL STREET BROOKLYN 11212',
 '518 BRISTOL STREET BROOKLYN 11212',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '246 PRESIDENT STREET BROOKLYN 11231',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '1759 BAY RIDGE PARKWAY BROOKLYN 11204',
 '1759 BAY RIDGE PARKWAY BROOKLYN 11204',
 '1759 BAY RIDGE PARKWAY BROOKLYN 11204',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '10 MAPLE STREET BROOKLYN 11225',
 '250 EAST 29 STREET BROOKLYN 11226',
 '229 23 STREET BROOKLYN 11232',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '229 23 STREET BROOKLYN 11232',
 '8678 BAY PARKWAY BROOKLYN 11214',
 '113 LINDEN STREET BROOKLYN 11221',
 '1710 WEST 4 STREET BROOKLYN 11223',
 '8714 21 AVENUE BROOKLYN 11214',
 '62 ROCKAWAY AVENUE BROOKLYN 11233',
 '1700 BEDFORD AVENUE BROOKLYN 11225',
 '324 CENTRAL AVENUE BROOKLYN 11221',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '8 COLUMBIA PLACE BROOKLYN 11201',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '451 KINGSTON AVENUE BROOKLYN 11225',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '203 MENAHAN STREET BROOKLYN 11237',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '118 CLARKSON AVENUE BROOKLYN 11226',
 '118 CLARKSON AVENUE BROOKLYN 11226',
 '1677 ST JOHNS PLACE BROOKLYN 11233',
 '664 WATKINS STREET BROOKLYN 11212',
 '1700 BEDFORD AVENUE BROOKLYN 11225',
 '946 BUSHWICK AVENUE BROOKLYN 11221',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '225 23 STREET BROOKLYN 11232',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '1202 AVENUE K BROOKLYN 11230',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '15 CROOKE AVENUE BROOKLYN 11226',
 '2211 DITMAS AVENUE BROOKLYN 11226',
 '2211 DITMAS AVENUE BROOKLYN 11226',
 '15 CROOKE AVENUE BROOKLYN 11226',
 '2211 DITMAS AVENUE BROOKLYN 11226',
 '2211 DITMAS AVENUE BROOKLYN 11226',
 '287 EAST 18 STREET BROOKLYN 11226',
 '246 PRESIDENT STREET BROOKLYN 11231',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '8202 3 AVENUE BROOKLYN 11209',
 '55 LENOX ROAD BROOKLYN 11226',
 '774 ROCKAWAY AVENUE BROOKLYN 11212',
 '86 COFFEY STREET BROOKLYN 11231',
 '56 ROCKAWAY PARKWAY BROOKLYN 11212',
 '56 ROCKAWAY PARKWAY BROOKLYN 11212',
 '34 MELROSE STREET BROOKLYN 11206',
 '34 MELROSE STREET BROOKLYN 11206',
 '2211 DITMAS AVENUE BROOKLYN 11226',
 '55 LENOX ROAD BROOKLYN 11226',
 '111 LINDEN STREET BROOKLYN 11221',
 '2076 20 LANE BROOKLYN 11214',
 '3412 ATLANTIC AVENUE BROOKLYN 11208',
 '34 MELROSE STREET BROOKLYN 11206',
 '155 LINDEN BOULEVARD BROOKLYN 11226',
 '1780 77 STREET BROOKLYN 11214',
 '156 GRAHAM AVENUE BROOKLYN 11206',
 '2211 DITMAS AVENUE BROOKLYN 11226',
 '2211 DITMAS AVENUE BROOKLYN 11226',
 '104 PULASKI STREET BROOKLYN 11206',
 '552 FLATBUSH AVENUE BROOKLYN 11225',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '34 MELROSE STREET BROOKLYN 11206',
 '964 HEMLOCK STREET BROOKLYN 11208',
 '34 MELROSE STREET BROOKLYN 11206',
 '34 MELROSE STREET BROOKLYN 11206',
 '34 MELROSE STREET BROOKLYN 11206',
 '1351 EASTERN PARKWAY BROOKLYN 11233',
 '377 MONTGOMERY STREET BROOKLYN 11225',
 '388 13 STREET BROOKLYN 11215',
 '964 HEMLOCK STREET BROOKLYN 11208',
 '377 MONTGOMERY STREET BROOKLYN 11225',
 '764 JEFFERSON AVENUE BROOKLYN 11221',
 '268 DECATUR STREET BROOKLYN 11233',
 '88 KINGSTON AVENUE BROOKLYN 11213',
 '151 CONOVER STREET BROOKLYN 11231',
 '151 CONOVER STREET BROOKLYN 11231',
 '770 HENDRIX STREET BROOKLYN 11207',
 '556 QUINCY STREET BROOKLYN 11221',
 '950 BERGEN STREET BROOKLYN 11216',
 '2462 PITKIN AVENUE BROOKLYN 11208',
 '28 PAERDEGAT 7 STREET BROOKLYN 11236',
 '1780 77 STREET BROOKLYN 11214',
 '5203 5 AVENUE BROOKLYN 11220',
 '88 KINGSTON AVENUE BROOKLYN 11213',
 '764 JEFFERSON AVENUE BROOKLYN 11221',
 '764 JEFFERSON AVENUE BROOKLYN 11221',
 '533 DAHILL ROAD BROOKLYN 11218',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '575 RIVERDALE AVENUE BROOKLYN 11207',
 '277 DAHILL ROAD BROOKLYN 11218',
 '2076 20 LANE BROOKLYN 11214',
 '433 LINCOLN AVENUE BROOKLYN 11208',
 '1166 FULTON STREET BROOKLYN 11216',
 '151 CONOVER STREET BROOKLYN 11231',
 '151 CONOVER STREET BROOKLYN 11231',
 '151 CONOVER STREET BROOKLYN 11231',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '464 CLINTON AVENUE BROOKLYN 11238',
 '174 CLINTON AVENUE BROOKLYN 11205',
 '710 EAST 93 STREET BROOKLYN 11236',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '802 DRIGGS AVENUE BROOKLYN 11211',
 '802 DRIGGS AVENUE BROOKLYN 11211',
 '802 DRIGGS AVENUE BROOKLYN 11211',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '780 LIVONIA AVENUE BROOKLYN 11207',
 '1202 AVENUE K BROOKLYN 11230',
 '580 EMPIRE BOULEVARD BROOKLYN 11225',
 '87 CARLTON AVENUE BROOKLYN 11205',
 '87 CARLTON AVENUE BROOKLYN 11205',
 '87 CARLTON AVENUE BROOKLYN 11205',
 '1700 BEDFORD AVENUE BROOKLYN 11225',
 '1610 AVENUE P BROOKLYN 11229',
 '338 SOUTH 3 STREET BROOKLYN 11211',
 '1700 BEDFORD AVENUE BROOKLYN 11225',
 '964 HEMLOCK STREET BROOKLYN 11208',
 '145 LINCOLN ROAD BROOKLYN 11225',
 '959 EAST 108 STREET BROOKLYN 11236',
 '1539 58 STREET BROOKLYN 11219',
 '55 LENOX ROAD BROOKLYN 11226',
 '317 JEFFERSON AVENUE BROOKLYN 11216',
 '170 HAWTHORNE STREET BROOKLYN 11225',
 '2211 DITMAS AVENUE BROOKLYN 11226',
 '2211 DITMAS AVENUE BROOKLYN 11226',
 '78 HAVEMEYER STREET BROOKLYN 11211',
 '141 HULL STREET BROOKLYN 11233',
 '1788 NOSTRAND AVENUE BROOKLYN 11226',
 '977 GREENE AVENUE BROOKLYN 11221',
 '977 GREENE AVENUE BROOKLYN 11221',
 '2904 ATLANTIC AVENUE BROOKLYN 11207',
 '1275 EAST 5 STREET BROOKLYN 11230',
 '977 GREENE AVENUE BROOKLYN 11221',
 '2100 WESTBURY COURT BROOKLYN 11225',
 '859 HALSEY STREET BROOKLYN 11233',
 '210 PATCHEN AVENUE BROOKLYN 11233',
 '1193 ROGERS AVENUE BROOKLYN 11226',
 '181 ROCKAWAY PARKWAY BROOKLYN 11212',
 '181 ROCKAWAY PARKWAY BROOKLYN 11212',
 '1292 STERLING PLACE BROOKLYN 11213',
 '15 CROOKE AVENUE BROOKLYN 11226',
 '2211 DITMAS AVENUE BROOKLYN 11226',
 '15 CROOKE AVENUE BROOKLYN 11226',
 '15 CROOKE AVENUE BROOKLYN 11226',
 '8714 21 AVENUE BROOKLYN 11214',
 '15 CROOKE AVENUE BROOKLYN 11226',
 '1292 STERLING PLACE BROOKLYN 11213',
 '1165 ELTON STREET BROOKLYN 11208',
 '137 14 STREET BROOKLYN 11215',
 '2575 BEDFORD AVENUE BROOKLYN 11226',
 '1517 40 STREET BROOKLYN 11218',
 '364 SOUTH 1 STREET BROOKLYN 11211',
 '4420 3 AVENUE BROOKLYN 11220',
 '95 FOUNTAIN AVENUE BROOKLYN 11208',
 '207 SUNNYSIDE AVENUE BROOKLYN 11207',
 '454 UNION AVENUE BROOKLYN 11211',
 '764 JEFFERSON AVENUE BROOKLYN 11221',
 '764 JEFFERSON AVENUE BROOKLYN 11221',
 '469 TOMPKINS AVENUE BROOKLYN 11216',
 '290 ARLINGTON AVENUE BROOKLYN 11208',
 '668 HANCOCK STREET BROOKLYN 11233',
 '553 BROOKLYN AVENUE BROOKLYN 11225',
 '563 NEW LOTS AVENUE BROOKLYN 11207',
 '28 COLUMBIA PLACE BROOKLYN 11201',
 '8714 21 AVENUE BROOKLYN 11214',
 '37 NEW LOTS AVENUE BROOKLYN 11212',
 '451 KINGSTON AVENUE BROOKLYN 11225',
 '451 KINGSTON AVENUE BROOKLYN 11225',
 '37 NEW LOTS AVENUE BROOKLYN 11212',
 '8714 21 AVENUE BROOKLYN 11214',
 '2955 BRIGHTON 7 STREET BROOKLYN 11235',
 '2955 BRIGHTON 7 STREET BROOKLYN 11235',
 '93 6 AVENUE BROOKLYN 11217',
 '37 NEW LOTS AVENUE BROOKLYN 11212',
 '1106 REMSEN AVENUE BROOKLYN 11236',
 '2950 WEST 24 STREET BROOKLYN 11224',
 '860 MACON STREET BROOKLYN 11233',
 '3205 EMMONS AVENUE BROOKLYN 11235',
 '596 ROGERS AVENUE BROOKLYN 11225',
 '388 13 STREET BROOKLYN 11215',
 '416 68 STREET BROOKLYN 11220',
 '308 ELLERY STREET BROOKLYN 11206',
 '2670 EAST 18 STREET BROOKLYN 11235',
 '2670 EAST 18 STREET BROOKLYN 11235',
 '268 DECATUR STREET BROOKLYN 11233',
 '88 KINGSTON AVENUE BROOKLYN 11213',
 '106 JAVA STREET BROOKLYN 11222',
 '451 JEFFERSON AVENUE BROOKLYN 11221',
 '312 LINCOLN ROAD BROOKLYN 11225',
 '770 HENDRIX STREET BROOKLYN 11207',
 '556 QUINCY STREET BROOKLYN 11221',
 '2462 PITKIN AVENUE BROOKLYN 11208',
 '88 KINGSTON AVENUE BROOKLYN 11213',
 '212 MESEROLE STREET BROOKLYN 11206',
 '401 EAST 96 STREET BROOKLYN 11212',
 '401 EAST 96 STREET BROOKLYN 11212',
 '555 OCEAN AVENUE BROOKLYN 11226',
 '308 ELLERY STREET BROOKLYN 11206',
 '110 CATON AVENUE BROOKLYN 11218',
 '642 VERMONT STREET BROOKLYN 11207',
 '642 VERMONT STREET BROOKLYN 11207',
 '642 VERMONT STREET BROOKLYN 11207',
 '110 CATON AVENUE BROOKLYN 11218',
 '308 ELLERY STREET BROOKLYN 11206',
 '146 17 STREET BROOKLYN 11215',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '575 HERKIMER STREET BROOKLYN 11213',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '203 MENAHAN STREET BROOKLYN 11237',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '642 VERMONT STREET BROOKLYN 11207',
 '642 VERMONT STREET BROOKLYN 11207',
 '642 VERMONT STREET BROOKLYN 11207',
 '642 VERMONT STREET BROOKLYN 11207',
 '402 TOMPKINS AVENUE BROOKLYN 11216',
 '575 HERKIMER STREET BROOKLYN 11213',
 '2784 EAST 12 STREET BROOKLYN 11235',
 '827 MONROE STREET BROOKLYN 11221',
 '1140 PACIFIC STREET BROOKLYN 11216',
 '675 HALSEY STREET BROOKLYN 11233',
 '1415 AVENUE O BROOKLYN 11230',
 '87 CARLTON AVENUE BROOKLYN 11205',
 '87 CARLTON AVENUE BROOKLYN 11205',
 '642 VERMONT STREET BROOKLYN 11207',
 '642 VERMONT STREET BROOKLYN 11207',
 '642 VERMONT STREET BROOKLYN 11207',
 '642 VERMONT STREET BROOKLYN 11207',
 '642 VERMONT STREET BROOKLYN 11207',
 '308 ELLERY STREET BROOKLYN 11206',
 '118 COOPER STREET BROOKLYN 11207',
 '4103 7 AVENUE BROOKLYN 11232',
 '15 CROOKE AVENUE BROOKLYN 11226',
 '1655 55 STREET BROOKLYN 11204',
 '180 ATKINS AVENUE BROOKLYN 11208',
 '246 PRESIDENT STREET BROOKLYN 11231',
 '764 JEFFERSON AVENUE BROOKLYN 11221',
 '1368 57 STREET BROOKLYN 11219',
 '1368 57 STREET BROOKLYN 11219',
 '1368 57 STREET BROOKLYN 11219',
 '15 CROOKE AVENUE BROOKLYN 11226',
 '15 CROOKE AVENUE BROOKLYN 11226',
 '1358 47 STREET BROOKLYN 11219',
 '355 TOMPKINS AVENUE BROOKLYN 11216',
 '802 DRIGGS AVENUE BROOKLYN 11211',
 '802 DRIGGS AVENUE BROOKLYN 11211',
 '269 NEW JERSEY AVENUE BROOKLYN 11207',
 '180 ATKINS AVENUE BROOKLYN 11208',
 '36 KENILWORTH PLACE BROOKLYN 11210',
 '764 JEFFERSON AVENUE BROOKLYN 11221',
 '764 JEFFERSON AVENUE BROOKLYN 11221',
 '764 JEFFERSON AVENUE BROOKLYN 11221',
 '529 SNEDIKER AVENUE BROOKLYN 11207',
 '447 EAST 45 STREET BROOKLYN 11203',
 '447 EAST 45 STREET BROOKLYN 11203',
 '180 ATKINS AVENUE BROOKLYN 11208',
 '15 CROOKE AVENUE BROOKLYN 11226',
 '1700 BEDFORD AVENUE BROOKLYN 11225',
 '1700 BEDFORD AVENUE BROOKLYN 11225',
 '959 EAST 108 STREET BROOKLYN 11236',
 '1700 BEDFORD AVENUE BROOKLYN 11225',
 '1518 EASTERN PARKWAY EXTENSION BROOKLYN 11233',
 '1518 EASTERN PARKWAY EXTENSION BROOKLYN 11233',
 '1518 EASTERN PARKWAY EXTENSION BROOKLYN 11233',
 '1518 EASTERN PARKWAY EXTENSION BROOKLYN 11233',
 '1518 EASTERN PARKWAY EXTENSION BROOKLYN 11233',
 '567 50 STREET BROOKLYN 11220',
 '1700 BEDFORD AVENUE BROOKLYN 11225',
 '860 MACON STREET BROOKLYN 11233',
 '860 MACON STREET BROOKLYN 11233',
 '1530 EAST 18 STREET BROOKLYN 11230',
 '1530 EAST 18 STREET BROOKLYN 11230',
 '167 34 STREET BROOKLYN 11232',
 '167 34 STREET BROOKLYN 11232',
 '860 MACON STREET BROOKLYN 11233',
 '860 MACON STREET BROOKLYN 11233',
 '65 SOUTH 6 STREET BROOKLYN 11249',
 '158 NASSAU AVENUE BROOKLYN 11222',
 '339 ETNA STREET BROOKLYN 11208',
 '774 ROCKAWAY AVENUE BROOKLYN 11212',
 '774 ROCKAWAY AVENUE BROOKLYN 11212',
 '774 ROCKAWAY AVENUE BROOKLYN 11212',
 '110 CATON AVENUE BROOKLYN 11218',
 '110 CATON AVENUE BROOKLYN 11218',
 '774 ROCKAWAY AVENUE BROOKLYN 11212',
 '78 POWERS STREET BROOKLYN 11211',
 '764 JEFFERSON AVENUE BROOKLYN 11221',
 '764 JEFFERSON AVENUE BROOKLYN 11221',
 '143 PARKVILLE AVENUE BROOKLYN 11230',
 '93 HICKS STREET BROOKLYN 11201',
 '584 STERLING PLACE BROOKLYN 11238',
 '111 LINDEN STREET BROOKLYN 11221',
 '111 LINDEN STREET BROOKLYN 11221',
 '77 HALSEY STREET BROOKLYN 11216',
 '146 17 STREET BROOKLYN 11215',
 '2017 CHURCH AVENUE BROOKLYN 11226',
 '355 EAST 48 STREET BROOKLYN 11203',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '308 ELLERY STREET BROOKLYN 11206',
 '2143 WEST STREET BROOKLYN 11223',
 '308 ELLERY STREET BROOKLYN 11206',
 '15 CROOKE AVENUE BROOKLYN 11226',
 '15 CROOKE AVENUE BROOKLYN 11226',
 '15 CROOKE AVENUE BROOKLYN 11226',
 '1401 NEW YORK AVENUE BROOKLYN 11210',
 '60 BAY 47 STREET BROOKLYN 11214',
 '60 BAY 47 STREET BROOKLYN 11214',
 '60 BAY 47 STREET BROOKLYN 11214',
 '60 BAY 47 STREET BROOKLYN 11214',
 '2718 PITKIN AVENUE BROOKLYN 11208',
 '2775 EAST 12 STREET BROOKLYN 11235',
 '224 HIGHLAND BOULEVARD BROOKLYN 11207',
 '8797 25 AVENUE BROOKLYN 11214',
 '12 VERNON AVENUE BROOKLYN 11206',
 '155 OCEANA DRIVE EAST BROOKLYN 11235',
 '155 OCEANA DRIVE EAST BROOKLYN 11235',
 '155 OCEANA DRIVE EAST BROOKLYN 11235',
 '155 OCEANA DRIVE EAST BROOKLYN 11235',
 '308 ELLERY STREET BROOKLYN 11206',